from __future__ import annotations

LANGUAGES = [
    ("pt-BR", "Português (Brasil)"),
    ("en", "English"),
    ("es", "Español"),
]

MEMORY_CARDS = [
    {"id": "standard", "family": "mc", "name": "Standard PS2 Memory Card / MagicGate compatible"},
    {"id": "sd2psx", "family": "mmce", "name": "SD2PSX"},
    {"id": "memcard-pro2", "family": "mmce", "name": "MemCard PRO2"},
    {"id": "psxmemcard-gen2", "family": "mmce", "name": "PSxMemCard Gen2"},
    {"id": "other-mmce", "family": "mmce", "name": "Other MMCE-compatible Memory Card"},
]

STORAGES = [
    {"id": "mmce", "name": "MMCE storage"},
    {"id": "mx4sio", "name": "MX4SIO"},
    {"id": "usb", "name": "USB"},
    {"id": "hdd-exfat", "name": "Internal HDD (exFAT / BDM)"},
    {"id": "hdd-apa", "name": "Internal HDD (APA/PFS) — choose partition next"},
]

TEXT: dict[str, dict[str, str]] = {
    "pt-BR": {
        "intro": "Este assistente baixa os homebrews escolhidos e monta duas pastas prontas: uma para o Memory Card/VMC e outra para o armazenamento de APPS. Ele não copia nada diretamente para o PS2.",
        "step_output": "Pasta de saída",
        "step_hardware": "Seu setup",
        "step_apps": "Homebrews",
        "step_summary": "Resumo",
        "step_download": "Downloads",
        "step_package": "Pacote final",
        "output_help": "Escolha onde os downloads, selection.json e o pacote final serão criados.",
        "output_location": "Onde você quer salvar a saída?",
        "output_project": "Junto do projeto (./output)",
        "output_custom": "Escolher outra pasta",
        "custom_output": "Digite o caminho da pasta de saída",
        "output_error": "Não foi possível usar essa pasta: {error}",
        "output_selected": "Saída: {path}",
        "hardware_help": "PS2BBL e as configurações vão para o Memory Card/VMC. OSDMenu e APPS ficam no armazenamento maior.",
        "memory_card": "Qual Memory Card você usa?",
        "storage": "Onde OSDMenu e os homebrews devem ficar?",
        "hdd_apa_partition": "Qual partição PFS deve armazenar APPS?",
        "hdd_apa_opl": "+OPL (padrão do OPL; recomendado para integração com APPS)",
        "hdd_apa_common": "__common",
        "hdd_apa_custom": "Outra partição PFS",
        "hdd_apa_custom_prompt": "Nome exato da partição APA/PFS",
        "hdd_apa_invalid": "Nome de partição inválido. Não use : / ou \\ e limite a 32 caracteres.",
        "hdd_apa_selected": "Partição PFS: {partition}",
        "hdd_exfat_notice": "HDD exFAT usa ata:/ no OSDMenu/OPL. O PS2BBL oficial empacotado não terá R1 apontando para ata:/ até esse caminho ser validado no build oficial; o pacote será gerado com aviso.",
        "apps_help": "Componentes obrigatórios entram automaticamente. Para os opcionais, responda Y/N; quando houver stable/beta, você escolhe o canal.",
        "install": "Instalar {name}?",
        "required": "Obrigatório neste modo",
        "resolving": "Consultando versões atuais no GitHub...",
        "resolve_failed": "Não foi possível consultar {name}: {error}",
        "available": "Versões disponíveis",
        "choose_channel": "Escolha a versão de {name}",
        "saved": "Plano: {path}",
        "card": "Memory Card",
        "selected_storage": "Armazenamento",
        "selected_apps": "Selecionados",
        "none": "nenhum opcional",
        "invalid": "Opção inválida. Tente novamente.",
        "download": "Baixar agora os arquivos selecionados?",
        "dependency_check": "Verificando dependências para extrair pacotes .7z...",
        "dependency_install": "Nenhum 7z nativo encontrado. Tentando py7zr no desktop...",
        "dependency_ok": "Backend 7z pronto para uso.",
        "dependency_fail": "Não consegui preparar um backend 7z automaticamente: {error}",
        "dependency_manual": "Instale 7-Zip. No Termux: pkg install 7zip",
        "native_7z": "7-Zip nativo encontrado: {path}",
        "termux_7z_missing": "7-Zip não encontrado no Android/Termux. Instale com: pkg install 7zip",
        "skipped": "Etapa omitida.",
        "package_warning": "Aviso: {warning}",
        "downloading": "{name} {version}",
        "downloaded": "{name} baixado e preparado",
        "download_failed": "Falha em {name}: {error}",
        "download_warning": "{name}: {warning}",
        "unresolved": "Sem versão resolvida; ficará apenas no plano.",
        "generate_package": "Gerar agora as pastas prontas para copiar?",
        "package_ready": "PACOTE PRONTO",
        "package_incomplete": "PACOTE INCOMPLETO — não copie para o PS2 ainda",
        "package_failed": "Falha ao gerar o pacote: {error}",
        "missing": "Faltando: {items}",
        "package_path": "Pacote: {path}",
        "done": "Concluído.",
    },
    "en": {
        "intro": "This assistant downloads the selected homebrew and builds two ready-to-copy folders: one for the Memory Card/VMC and one for APPS storage. It never writes directly to your PS2.",
        "step_output": "Output folder",
        "step_hardware": "Your setup",
        "step_apps": "Homebrew",
        "step_summary": "Summary",
        "step_download": "Downloads",
        "step_package": "Final package",
        "output_help": "Choose where downloads, selection.json and the final package will be created.",
        "output_location": "Where should the output be saved?",
        "output_project": "Inside the project (./output)",
        "output_custom": "Choose another folder",
        "custom_output": "Enter the output folder path",
        "output_error": "Could not use that folder: {error}",
        "output_selected": "Output: {path}",
        "hardware_help": "PS2BBL and configuration go to the Memory Card/VMC. OSDMenu and APPS stay on larger storage.",
        "memory_card": "Which Memory Card do you use?",
        "storage": "Where should OSDMenu and homebrew be stored?",
        "hdd_apa_partition": "Which PFS partition should store APPS?",
        "hdd_apa_opl": "+OPL (OPL default; recommended for APPS integration)",
        "hdd_apa_common": "__common",
        "hdd_apa_custom": "Another PFS partition",
        "hdd_apa_custom_prompt": "Exact APA/PFS partition name",
        "hdd_apa_invalid": "Invalid partition name. Do not use : / or \\ and keep it within 32 characters.",
        "hdd_apa_selected": "PFS partition: {partition}",
        "hdd_exfat_notice": "exFAT HDD uses ata:/ in OSDMenu/OPL. The packaged official PS2BBL build will not bind R1 to ata:/ until that path is verified on the official build; the package will be generated with a warning.",
        "apps_help": "Required components are included automatically. Optional apps use Y/N prompts; stable/beta choices are shown when available.",
        "install": "Install {name}?",
        "required": "Required for this mode",
        "resolving": "Checking current GitHub releases...",
        "resolve_failed": "Could not resolve {name}: {error}",
        "available": "Available versions",
        "choose_channel": "Choose the version of {name}",
        "saved": "Plan: {path}",
        "card": "Memory Card",
        "selected_storage": "Storage",
        "selected_apps": "Selected",
        "none": "no optional apps",
        "invalid": "Invalid option. Try again.",
        "download": "Download the selected files now?",
        "dependency_check": "Checking dependencies needed for .7z packages...",
        "dependency_install": "No native 7z was found. Trying py7zr on desktop...",
        "dependency_ok": "7z backend is ready.",
        "dependency_fail": "Could not prepare a 7z backend automatically: {error}",
        "dependency_manual": "Install 7-Zip. On Termux: pkg install 7zip",
        "native_7z": "Native 7-Zip found: {path}",
        "termux_7z_missing": "7-Zip was not found on Android/Termux. Install it with: pkg install 7zip",
        "skipped": "Step skipped.",
        "package_warning": "Warning: {warning}",
        "downloading": "{name} {version}",
        "downloaded": "{name} downloaded and prepared",
        "download_failed": "Failed {name}: {error}",
        "download_warning": "{name}: {warning}",
        "unresolved": "No resolved version; it will remain in the plan only.",
        "generate_package": "Generate the ready-to-copy folders now?",
        "package_ready": "PACKAGE READY",
        "package_incomplete": "INCOMPLETE PACKAGE — do not copy it to the PS2 yet",
        "package_failed": "Failed to generate package: {error}",
        "missing": "Missing: {items}",
        "package_path": "Package: {path}",
        "done": "Done.",
    },
    "es": {
        "intro": "Este asistente descarga los homebrews elegidos y crea dos carpetas listas para copiar: una para la Memory Card/VMC y otra para el almacenamiento de APPS. No escribe directamente en tu PS2.",
        "step_output": "Carpeta de salida",
        "step_hardware": "Tu setup",
        "step_apps": "Homebrews",
        "step_summary": "Resumen",
        "step_download": "Descargas",
        "step_package": "Paquete final",
        "output_help": "Elige dónde se crearán las descargas, selection.json y el paquete final.",
        "output_location": "¿Dónde quieres guardar la salida?",
        "output_project": "Dentro del proyecto (./output)",
        "output_custom": "Elegir otra carpeta",
        "custom_output": "Introduce la ruta de salida",
        "output_error": "No se pudo usar esa carpeta: {error}",
        "output_selected": "Salida: {path}",
        "hardware_help": "PS2BBL y las configuraciones van a la Memory Card/VMC. OSDMenu y APPS quedan en el almacenamiento grande.",
        "memory_card": "¿Qué Memory Card utilizas?",
        "storage": "¿Dónde deben guardarse OSDMenu y los homebrews?",
        "hdd_apa_partition": "¿Qué partición PFS debe almacenar APPS?",
        "hdd_apa_opl": "+OPL (predeterminada de OPL; recomendada para integración con APPS)",
        "hdd_apa_common": "__common",
        "hdd_apa_custom": "Otra partición PFS",
        "hdd_apa_custom_prompt": "Nombre exacto de la partición APA/PFS",
        "hdd_apa_invalid": "Nombre de partición inválido. No uses : / o \\ y limita a 32 caracteres.",
        "hdd_apa_selected": "Partición PFS: {partition}",
        "hdd_exfat_notice": "El HDD exFAT usa ata:/ en OSDMenu/OPL. El PS2BBL oficial empaquetado no enlazará R1 a ata:/ hasta validar esa ruta en el build oficial; el paquete se generará con una advertencia.",
        "apps_help": "Los componentes obligatorios se incluyen solos. Los opcionales usan Y/N; si hay stable/beta podrás elegir el canal.",
        "install": "¿Instalar {name}?",
        "required": "Obligatorio para este modo",
        "resolving": "Consultando releases actuales en GitHub...",
        "resolve_failed": "No se pudo consultar {name}: {error}",
        "available": "Versiones disponibles",
        "choose_channel": "Elige la versión de {name}",
        "saved": "Plan: {path}",
        "card": "Memory Card",
        "selected_storage": "Almacenamiento",
        "selected_apps": "Seleccionados",
        "none": "ningún opcional",
        "invalid": "Opción inválida. Inténtalo de nuevo.",
        "download": "¿Descargar ahora los archivos seleccionados?",
        "dependency_check": "Comprobando dependencias para paquetes .7z...",
        "dependency_install": "No se encontró 7z nativo. Probando py7zr en escritorio...",
        "dependency_ok": "El backend 7z está listo.",
        "dependency_fail": "No se pudo preparar un backend 7z automáticamente: {error}",
        "dependency_manual": "Instala 7-Zip. En Termux: pkg install 7zip",
        "native_7z": "7-Zip nativo encontrado: {path}",
        "termux_7z_missing": "No se encontró 7-Zip en Android/Termux. Instálalo con: pkg install 7zip",
        "skipped": "Etapa omitida.",
        "package_warning": "Advertencia: {warning}",
        "downloading": "{name} {version}",
        "downloaded": "{name} descargado y preparado",
        "download_failed": "Error en {name}: {error}",
        "download_warning": "{name}: {warning}",
        "unresolved": "Sin versión resuelta; quedará solo en el plan.",
        "generate_package": "¿Generar ahora las carpetas listas para copiar?",
        "package_ready": "PAQUETE LISTO",
        "package_incomplete": "PAQUETE INCOMPLETO — no lo copies todavía al PS2",
        "package_failed": "Error al generar el paquete: {error}",
        "missing": "Falta: {items}",
        "package_path": "Paquete: {path}",
        "done": "Completado.",
    },
}



# Selection/download UX added in catalog schema v6.
TEXT["pt-BR"].update({
    "apps_help": "Componentes obrigatórios entram automaticamente. Escolha vários opcionais de uma vez usando vírgulas; P pula direto aos downloads.",
    "resolving": "Consultando versões atuais no GitHub e fontes diretas...",
    "multi_help": "Ex.: 1,2 ou 1, 2. Enter usa os padrões. A seleciona todos. P pula direto aos Downloads; também funciona como 1,5,P.",
    "multi_prompt": "Selecione os homebrews/emuladores",
    "default_marker": "padrão",
    "manual_marker": "manual",
    "manual_selected": "{name}: fonte/instalação manual; será documentado no pacote.",
    "jumping_downloads": "Atalho P: indo direto para Downloads com os canais recomendados.",
    "downloads_temporary": "Downloads e extrações são temporários e serão apagados automaticamente ao terminar.",
    "downloads_kept": "Modo de depuração: downloads serão mantidos em {path}",
    "downloads_cleaned": "Downloads temporários apagados.",
})

TEXT["en"].update({
    "apps_help": "Required components are automatic. Select multiple optional apps at once with commas; P jumps straight to Downloads.",
    "resolving": "Checking current GitHub releases and direct sources...",
    "multi_help": "Example: 1,2 or 1, 2. Enter uses defaults. A selects all. P jumps straight to Downloads; 1,5,P also works.",
    "multi_prompt": "Select homebrew/emulators",
    "default_marker": "default",
    "manual_marker": "manual",
    "manual_selected": "{name}: manual source/setup; it will be documented in the package.",
    "jumping_downloads": "P shortcut: jumping directly to Downloads using recommended channels.",
    "downloads_temporary": "Downloads and extracted files are temporary and will be deleted automatically when finished.",
    "downloads_kept": "Debug mode: downloads will be kept at {path}",
    "downloads_cleaned": "Temporary downloads deleted.",
})

TEXT["es"].update({
    "apps_help": "Los componentes obligatorios son automáticos. Selecciona varios opcionales con comas; P salta directamente a Descargas.",
    "resolving": "Consultando versiones actuales en GitHub y fuentes directas...",
    "multi_help": "Ej.: 1,2 o 1, 2. Enter usa los predeterminados. A selecciona todos. P salta a Descargas; 1,5,P también funciona.",
    "multi_prompt": "Selecciona homebrews/emuladores",
    "default_marker": "predeterminado",
    "manual_marker": "manual",
    "manual_selected": "{name}: fuente/instalación manual; se documentará en el paquete.",
    "jumping_downloads": "Atajo P: saltando directamente a Descargas con los canales recomendados.",
    "downloads_temporary": "Las descargas y extracciones son temporales y se borrarán automáticamente al terminar.",
    "downloads_kept": "Modo de depuración: las descargas se conservarán en {path}",
    "downloads_cleaned": "Descargas temporales eliminadas.",
})

# Clarify that only the final artifacts are persistent by default.
TEXT["pt-BR"]["output_help"] = "Escolha onde selection.json e o pacote final serão criados. Downloads/extracões são temporários por padrão."
TEXT["en"]["output_help"] = "Choose where selection.json and the final package will be created. Downloads/extractions are temporary by default."
TEXT["es"]["output_help"] = "Elige dónde se crearán selection.json y el paquete final. Las descargas/extracciones son temporales por defecto."

# Workflow/boot/local import/update UX (schema v7).
TEXT["pt-BR"].update({
    "workflow_mode": "O que você quer fazer?",
    "workflow_new": "Criar um pacote novo (recomendado; não pede instalação existente)",
    "workflow_update": "Atualizar uma instalação JÁ EXISTENTE (avançado; pede as pastas montadas)",
    "workflow_selected": "Modo: {mode}",
    "boot_method": "Como o PS2BBL será iniciado?",
    "boot_existing": "Meu PS2 já executa ELF/homebrew (recomendado: FMCB, wLaunchELF, OPL, FreeDVDBoot etc.)",
    "boot_opentuna": "OpenTuna",
    "boot_dev1": "Modchip DEV1 (mc0:/BOOT/BOOT.ELF)",
    "boot_system_update": "System Update / KELF no Memory Card (avançado/opcional)",
    "boot_hdd_kelf": "Boot por HDD / KELF (HSYSTEM.XLF) (avançado/opcional)",
    "boot_selected": "Boot do PS2BBL: {method}",
    "boot_help": "O PS2BBL é um ELF normal. Se seu PS2 já executa homebrew, use a opção 1. OpenTuna/DEV1/KELF são apenas formas opcionais de iniciar o mesmo PS2BBL automaticamente.",
    "r1_osdmenu": "Configurar R1 no PS2BBL para abrir o OSDMenu?",
    "r1_exfat_unavailable": "HDD exFAT: o atalho R1 do PS2BBL fica desativado porque ata:/ ainda não está validado para o build oficial empacotado.",
    "update_paths_help": "Modo UPDATE: as próximas duas perguntas são somente as pastas reais de uma instalação já existente/montada. Elas NÃO têm relação com System Update/KELF. Se você queria apenas gerar um pacote novo, volte e escolha a opção 1.",
    "update_mc_path": "Raiz do Memory Card/VMC existente",
    "update_storage_path": "Raiz do armazenamento APPS existente",
    "existing_apps_found": "Apps existentes detectados: {count}",
    "remove_existing_prompt": "Remover algum app existente nesta atualização?",
    "remove_help": "Digite números separados por vírgula (ou A para todos). Enter não remove nada. Tudo removido é salvo no backup primeiro.",
    "rebuild_menus": "Reconstruir PS2BBL.INI/OSDMENU.CNF preservando os APPS existentes detectados?",
    "local_marker": "local",
    "local_help": "Importe um ou mais ELFs locais. Enter encerra a importação.",
    "local_path": "Caminho do ELF local (Enter para terminar)",
    "local_name": "Nome que aparecerá nos menus",
    "local_invalid": "Arquivo ELF local inválido: {path}",
    "local_added": "ELF local adicionado: {name} <- {path}",
    "local_more": "Adicionar outro ELF local?",
    "local_selected": "{name}: ELF local selecionado.",
    "local_prepared": "{name}: ELF local pronto para empacotar",
    "compatibility_header": "Compatibilidade / avisos conhecidos",
    "apply_update": "Aplicar agora o pacote na instalação existente? Um backup será criado antes.",
    "update_applied": "Instalação existente atualizada. Backup: {backup}",
    "update_failed": "Falha ao atualizar a instalação existente: {error}",
})

TEXT["en"].update({
    "workflow_mode": "What do you want to do?",
    "workflow_new": "Create a new package (recommended; no existing install paths required)",
    "workflow_update": "Update an EXISTING installation (advanced; requires mounted paths)",
    "workflow_selected": "Mode: {mode}",
    "boot_method": "How will PS2BBL be started?",
    "boot_existing": "My PS2 already runs ELF/homebrew (recommended: FMCB, wLaunchELF, OPL, FreeDVDBoot etc.)",
    "boot_opentuna": "OpenTuna",
    "boot_dev1": "Modchip DEV1 (mc0:/BOOT/BOOT.ELF)",
    "boot_system_update": "Memory Card System Update / KELF (advanced/optional)",
    "boot_hdd_kelf": "HDD / KELF boot (HSYSTEM.XLF) (advanced/optional)",
    "boot_selected": "PS2BBL boot: {method}",
    "boot_help": "PS2BBL is a normal ELF. If your PS2 already runs homebrew, choose option 1. OpenTuna/DEV1/KELF are only optional ways to start the same PS2BBL automatically.",
    "r1_osdmenu": "Bind R1 in PS2BBL to launch OSDMenu?",
    "r1_exfat_unavailable": "exFAT HDD: the PS2BBL R1 shortcut stays disabled because ata:/ is not yet verified for the packaged official build.",
    "update_paths_help": "UPDATE mode: the next two prompts are only the real mounted folders of an existing installation. They are NOT related to System Update/KELF. If you only wanted a new package, go back and choose option 1.",
    "update_mc_path": "Existing Memory Card/VMC root",
    "update_storage_path": "Existing APPS storage root",
    "existing_apps_found": "Existing apps detected: {count}",
    "remove_existing_prompt": "Remove any existing app during this update?",
    "remove_help": "Enter comma-separated numbers (or A for all). Enter removes nothing. Removed data is backed up first.",
    "rebuild_menus": "Rebuild PS2BBL.INI/OSDMENU.CNF while preserving detected existing APPS?",
    "local_marker": "local",
    "local_help": "Import one or more local ELF files. Press Enter to finish importing.",
    "local_path": "Local ELF path (Enter to finish)",
    "local_name": "Menu display name",
    "local_invalid": "Invalid local ELF file: {path}",
    "local_added": "Local ELF added: {name} <- {path}",
    "local_more": "Add another local ELF?",
    "local_selected": "{name}: local ELF selected.",
    "local_prepared": "{name}: local ELF ready to package",
    "compatibility_header": "Compatibility / known warnings",
    "apply_update": "Apply the package to the existing installation now? A backup will be created first.",
    "update_applied": "Existing installation updated. Backup: {backup}",
    "update_failed": "Failed to update the existing installation: {error}",
})

TEXT["es"].update({
    "workflow_mode": "¿Qué quieres hacer?",
    "workflow_new": "Crear un paquete nuevo (recomendado; no requiere instalación existente)",
    "workflow_update": "Actualizar una instalación YA EXISTENTE (avanzado; requiere rutas montadas)",
    "workflow_selected": "Modo: {mode}",
    "boot_method": "¿Cómo se iniciará PS2BBL?",
    "boot_existing": "Mi PS2 ya ejecuta ELF/homebrew (recomendado: FMCB, wLaunchELF, OPL, FreeDVDBoot etc.)",
    "boot_opentuna": "OpenTuna",
    "boot_dev1": "Modchip DEV1 (mc0:/BOOT/BOOT.ELF)",
    "boot_system_update": "System Update / KELF en Memory Card (avanzado/opcional)",
    "boot_hdd_kelf": "Arranque HDD / KELF (HSYSTEM.XLF) (avanzado/opcional)",
    "boot_selected": "Arranque PS2BBL: {method}",
    "boot_help": "PS2BBL es un ELF normal. Si tu PS2 ya ejecuta homebrew, usa la opción 1. OpenTuna/DEV1/KELF son solo formas opcionales de iniciar automáticamente el mismo PS2BBL.",
    "r1_osdmenu": "¿Configurar R1 en PS2BBL para abrir OSDMenu?",
    "r1_exfat_unavailable": "HDD exFAT: el acceso R1 de PS2BBL queda desactivado porque ata:/ aún no está validado para el build oficial empaquetado.",
    "update_paths_help": "Modo UPDATE: las próximas dos preguntas son solo las carpetas reales montadas de una instalación existente. NO están relacionadas con System Update/KELF. Si solo querías crear un paquete nuevo, vuelve y elige la opción 1.",
    "update_mc_path": "Raíz de Memory Card/VMC existente",
    "update_storage_path": "Raíz del almacenamiento APPS existente",
    "existing_apps_found": "Apps existentes detectadas: {count}",
    "remove_existing_prompt": "¿Eliminar alguna app existente durante esta actualización?",
    "remove_help": "Introduce números separados por comas (o A para todas). Enter no elimina nada. Todo se copia al backup antes.",
    "rebuild_menus": "¿Reconstruir PS2BBL.INI/OSDMENU.CNF preservando las APPS existentes detectadas?",
    "local_marker": "local",
    "local_help": "Importa uno o más ELF locales. Enter termina la importación.",
    "local_path": "Ruta del ELF local (Enter para terminar)",
    "local_name": "Nombre mostrado en los menús",
    "local_invalid": "Archivo ELF local inválido: {path}",
    "local_added": "ELF local añadido: {name} <- {path}",
    "local_more": "¿Añadir otro ELF local?",
    "local_selected": "{name}: ELF local seleccionado.",
    "local_prepared": "{name}: ELF local listo para empaquetar",
    "compatibility_header": "Compatibilidad / avisos conocidos",
    "apply_update": "¿Aplicar ahora el paquete a la instalación existente? Se creará un backup antes.",
    "update_applied": "Instalación existente actualizada. Backup: {backup}",
    "update_failed": "Error al actualizar la instalación existente: {error}",
})

TEXT["pt-BR"]["multi_help"] = "Ex.: 1,2 ou 1, 2. Enter usa os padrões. A seleciona todos. L importa ELF local. P pula aos Downloads; 1,5,L,P também funciona."
TEXT["en"]["multi_help"] = "Example: 1,2 or 1, 2. Enter uses defaults. A selects all. L imports a local ELF. P jumps to Downloads; 1,5,L,P also works."
TEXT["es"]["multi_help"] = "Ej.: 1,2 o 1, 2. Enter usa los predeterminados. A selecciona todos. L importa un ELF local. P salta a Descargas; 1,5,L,P también funciona."

TEXT["pt-BR"]["update_boot_elf"] = "Atualizar também BOOT/BOOT.ELF no Memory Card? (pode ser outro launcher em instalações antigas)"
TEXT["en"]["update_boot_elf"] = "Also update BOOT/BOOT.ELF on the Memory Card? (older setups may use that path for another launcher)"
TEXT["es"]["update_boot_elf"] = "¿Actualizar también BOOT/BOOT.ELF en la Memory Card? (instalaciones antiguas pueden usar esa ruta para otro launcher)"
