from __future__ import annotations

LANGUAGES = [
    ("pt-BR", "Português (Brasil)"),
    ("en", "English"),
    ("es", "Español"),
]

MEMORY_CARDS = [
    {"id": "standard", "family": "mc", "name": "Standard PS2 Memory Card / MagicGate compatible"},
    {"id": "sd2psx", "family": "mmce", "name": "SD2PSX"},
    {"id": "memcard-pro2", "family": "mmce", "name": "MemCard PRO2"},
    {"id": "psxmemcard-gen2", "family": "mmce", "name": "PSxMemCard Gen2"},
    {"id": "other-mmce", "family": "mmce", "name": "Other MMCE-compatible Memory Card"},
]

STORAGES = [
    {"id": "mmce", "name": "MMCE storage"},
    {"id": "mx4sio", "name": "MX4SIO"},
    {"id": "usb", "name": "USB"},
    {"id": "hdd-exfat", "name": "Internal HDD (exFAT)"},
    {"id": "hdd-apa", "name": "Internal HDD (APA/PFS)"},
]

TEXT: dict[str, dict[str, str]] = {
    "pt-BR": {
        "intro": "Este assistente baixa os homebrews escolhidos e monta duas pastas prontas: uma para o Memory Card/VMC e outra para o armazenamento de APPS. Ele não copia nada diretamente para o PS2.",
        "step_output": "Pasta de saída",
        "step_hardware": "Seu setup",
        "step_apps": "Homebrews",
        "step_summary": "Resumo",
        "step_download": "Downloads",
        "step_package": "Pacote final",
        "output_help": "Escolha onde os downloads, selection.json e o pacote final serão criados.",
        "output_location": "Onde você quer salvar a saída?",
        "output_project": "Junto do projeto (./output)",
        "output_custom": "Escolher outra pasta",
        "custom_output": "Digite o caminho da pasta de saída",
        "output_error": "Não foi possível usar essa pasta: {error}",
        "output_selected": "Saída: {path}",
        "hardware_help": "PS2BBL e as configurações vão para o Memory Card/VMC. OSDMenu e APPS ficam no armazenamento maior.",
        "memory_card": "Qual Memory Card você usa?",
        "storage": "Onde OSDMenu e os homebrews devem ficar?",
        "apps_help": "Componentes obrigatórios entram automaticamente. Para os opcionais, responda Y/N; quando houver stable/beta, você escolhe o canal.",
        "install": "Instalar {name}?",
        "required": "Obrigatório neste modo",
        "resolving": "Consultando versões atuais no GitHub...",
        "resolve_failed": "Não foi possível consultar {name}: {error}",
        "available": "Versões disponíveis",
        "choose_channel": "Escolha a versão de {name}",
        "saved": "Plano: {path}",
        "card": "Memory Card",
        "selected_storage": "Armazenamento",
        "selected_apps": "Selecionados",
        "none": "nenhum opcional",
        "invalid": "Opção inválida. Tente novamente.",
        "download": "Baixar agora os arquivos selecionados?",
        "dependency_check": "Verificando dependências para extrair pacotes .7z...",
        "dependency_install": "py7zr não está instalado. Instalando automaticamente com pip...",
        "dependency_ok": "py7zr pronto para uso.",
        "dependency_fail": "Não consegui instalar py7zr automaticamente: {error}",
        "dependency_manual": "Instale manualmente com: python -m pip install -r requirements.txt",
        "downloading": "{name} {version}",
        "downloaded": "{name} baixado e preparado",
        "download_failed": "Falha em {name}: {error}",
        "download_warning": "{name}: {warning}",
        "unresolved": "Sem versão resolvida; ficará apenas no plano.",
        "generate_package": "Gerar agora as pastas prontas para copiar?",
        "package_ready": "PACOTE PRONTO",
        "package_incomplete": "PACOTE INCOMPLETO — não copie para o PS2 ainda",
        "package_failed": "Falha ao gerar o pacote: {error}",
        "missing": "Faltando: {items}",
        "package_path": "Pacote: {path}",
        "done": "Concluído.",
    },
    "en": {
        "intro": "This assistant downloads the selected homebrew and builds two ready-to-copy folders: one for the Memory Card/VMC and one for APPS storage. It never writes directly to your PS2.",
        "step_output": "Output folder",
        "step_hardware": "Your setup",
        "step_apps": "Homebrew",
        "step_summary": "Summary",
        "step_download": "Downloads",
        "step_package": "Final package",
        "output_help": "Choose where downloads, selection.json and the final package will be created.",
        "output_location": "Where should the output be saved?",
        "output_project": "Inside the project (./output)",
        "output_custom": "Choose another folder",
        "custom_output": "Enter the output folder path",
        "output_error": "Could not use that folder: {error}",
        "output_selected": "Output: {path}",
        "hardware_help": "PS2BBL and configuration go to the Memory Card/VMC. OSDMenu and APPS stay on larger storage.",
        "memory_card": "Which Memory Card do you use?",
        "storage": "Where should OSDMenu and homebrew be stored?",
        "apps_help": "Required components are included automatically. Optional apps use Y/N prompts; stable/beta choices are shown when available.",
        "install": "Install {name}?",
        "required": "Required for this mode",
        "resolving": "Checking current GitHub releases...",
        "resolve_failed": "Could not resolve {name}: {error}",
        "available": "Available versions",
        "choose_channel": "Choose the version of {name}",
        "saved": "Plan: {path}",
        "card": "Memory Card",
        "selected_storage": "Storage",
        "selected_apps": "Selected",
        "none": "no optional apps",
        "invalid": "Invalid option. Try again.",
        "download": "Download the selected files now?",
        "dependency_check": "Checking dependencies needed for .7z packages...",
        "dependency_install": "py7zr is missing. Installing it automatically with pip...",
        "dependency_ok": "py7zr is ready.",
        "dependency_fail": "Could not install py7zr automatically: {error}",
        "dependency_manual": "Install it manually with: python -m pip install -r requirements.txt",
        "downloading": "{name} {version}",
        "downloaded": "{name} downloaded and prepared",
        "download_failed": "Failed {name}: {error}",
        "download_warning": "{name}: {warning}",
        "unresolved": "No resolved version; it will remain in the plan only.",
        "generate_package": "Generate the ready-to-copy folders now?",
        "package_ready": "PACKAGE READY",
        "package_incomplete": "INCOMPLETE PACKAGE — do not copy it to the PS2 yet",
        "package_failed": "Failed to generate package: {error}",
        "missing": "Missing: {items}",
        "package_path": "Package: {path}",
        "done": "Done.",
    },
    "es": {
        "intro": "Este asistente descarga los homebrews elegidos y crea dos carpetas listas para copiar: una para la Memory Card/VMC y otra para el almacenamiento de APPS. No escribe directamente en tu PS2.",
        "step_output": "Carpeta de salida",
        "step_hardware": "Tu setup",
        "step_apps": "Homebrews",
        "step_summary": "Resumen",
        "step_download": "Descargas",
        "step_package": "Paquete final",
        "output_help": "Elige dónde se crearán las descargas, selection.json y el paquete final.",
        "output_location": "¿Dónde quieres guardar la salida?",
        "output_project": "Dentro del proyecto (./output)",
        "output_custom": "Elegir otra carpeta",
        "custom_output": "Introduce la ruta de salida",
        "output_error": "No se pudo usar esa carpeta: {error}",
        "output_selected": "Salida: {path}",
        "hardware_help": "PS2BBL y las configuraciones van a la Memory Card/VMC. OSDMenu y APPS quedan en el almacenamiento grande.",
        "memory_card": "¿Qué Memory Card utilizas?",
        "storage": "¿Dónde deben guardarse OSDMenu y los homebrews?",
        "apps_help": "Los componentes obligatorios se incluyen solos. Los opcionales usan Y/N; si hay stable/beta podrás elegir el canal.",
        "install": "¿Instalar {name}?",
        "required": "Obligatorio para este modo",
        "resolving": "Consultando releases actuales en GitHub...",
        "resolve_failed": "No se pudo consultar {name}: {error}",
        "available": "Versiones disponibles",
        "choose_channel": "Elige la versión de {name}",
        "saved": "Plan: {path}",
        "card": "Memory Card",
        "selected_storage": "Almacenamiento",
        "selected_apps": "Seleccionados",
        "none": "ningún opcional",
        "invalid": "Opción inválida. Inténtalo de nuevo.",
        "download": "¿Descargar ahora los archivos seleccionados?",
        "dependency_check": "Comprobando dependencias para paquetes .7z...",
        "dependency_install": "Falta py7zr. Instalándolo automáticamente con pip...",
        "dependency_ok": "py7zr está listo.",
        "dependency_fail": "No se pudo instalar py7zr automáticamente: {error}",
        "dependency_manual": "Instálalo manualmente con: python -m pip install -r requirements.txt",
        "downloading": "{name} {version}",
        "downloaded": "{name} descargado y preparado",
        "download_failed": "Error en {name}: {error}",
        "download_warning": "{name}: {warning}",
        "unresolved": "Sin versión resuelta; quedará solo en el plan.",
        "generate_package": "¿Generar ahora las carpetas listas para copiar?",
        "package_ready": "PAQUETE LISTO",
        "package_incomplete": "PAQUETE INCOMPLETO — no lo copies todavía al PS2",
        "package_failed": "Error al generar el paquete: {error}",
        "missing": "Falta: {items}",
        "package_path": "Paquete: {path}",
        "done": "Completado.",
    },
}


